language: node_js
node_js:
- 6
script: npm run build ; npm test
install:
- npm i -g npm@latest
- npm install
- cd client
- npm install
- cd ..
- npm install jest-cli
- touch .env
services:
- mongodb
env:
- MONGODBURI=localhost:27017/smsup SUPPORTED_LOCALES=en,fa ACTIVE_GATEWAY=nexmo
notifications:
  email:
    on_failure: change
cache:
  directories:
  - node_modules
  - client/node_modules
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: PWt7jXsxuhMFXs+qdBr1fqwIDeo09KIKUi7zIOACee/EUq1fEt06skKwLSNKAtS2KkF2mKkT0qJG6z7Rege0nPwc+qsn0NOK/VoCQhanq8GkxNNpqULXrK5pcILCsczNjmROkAQYrpuJVWO4noQ2d/SHWclCtjbiOvUIEauiQGgHG50sVHZ5E6TdDexDmEX8+Aj+uJnVZB6mHB20s+aysV+bNwQUtdKVEBALD1sBXXF1DjFYqPyydQW4cfT9bF9To8NgozXPAUD6RiIgXm9ixXsl1iIwvB7X7nu9vTJxuxP86MbkBp/n/xc9Gd1z8mweKbVLfn2kqBHCp+Er5MgS+4EnNodheG4QBN4cd/xj8lYf5afzeiyg9bbPO3ELcZvY3TT/Ckuy5mnV5Szx/pV1yzClxMCmaBUzA6FKiwt7cJn1zNr/1Vrvil9Cf+/l07QbQI5hFozwS7DEI+WMFY8pV60kmfQ36nLV6XmuAFd052Fnf6Om7RwSzT/6aio7KY5V1bsK0hE5d7sPIcOdBgk3VrtP8Jhxl2pvWjVjgOcQLzsXqcapl9r5DZhk/3FAZlAV1t8MC8saJgsY04TJ7ya5VSC2QlNuS+qdTR8uh3jPLg4EiULXWaQZ48pthE6Q5ROLhk2TArnSBvE8Jj/IQl+Bb+ttMITzMInG2WyRIUID5BE=
  app: smsup
  on:
    repo: duncanfwalker/smsup
